#! /usr/bin/env bash

# Create a list of files that should be unlinked.
files=(
    "$HOME/.bashrc"
    "$HOME/.bash_styles"
    "$HOME/.bash_prompt"
    "$HOME/.bash_aliases"
    "$HOME/.bash_welcome"
    "$HOME/.bash_osx"
    "$HOME/.bash_ubuntu"
    "$HOME/.dircolors"
    "$HOME/.gitconfig"
    "$HOME/.gitprompt"
    "$HOME/.vim"
    "$HOME/.vimrc"
)

# Iterate the files and remove them as long as the file is a symlink.
for f in "${files[@]}"; do
    if [ -L "$f" ]; then
        rm -rf "$f"
    else
        echo "$f is not a symlink, skipping deletion."
    fi
done
