#! /usr/bin/env bash

files=(
    ~/.bashrc
    ~/.bash_styles
    ~/.bash_prompt
    ~/.bash_aliases
    ~/.bash_welcome
    ~/.bash_osx
    ~/.bash_ubuntu
    ~/.dircolors
    ~/.gitconfig
    ~/.gitprompt
    ~/.vim
    ~/.vimrc
)

for f in "${files[@]}"; do
    if [ -L "$f" ]; then
        rm -rf "$f"
    else
        echo "$f is not a symlink, skipping deletion."
    fi
done
