#! /usr/bin/env bash

files=(
    ~/.bashrc
    ~/.bash_styles
    ~/.bash_prompt
    ~/.bash_aliases
    ~/.bash_welcome
    ~/.bash_osx
    ~/.bash_ubuntu
    ~/.gitconfig
    ~/.git-prompt.sh
    ~/.vim
    ~/.vimrc
)

for f in ${files[@]}; do
    if [ -h ${f} ]; then
        rm -rf ${f}
    fi
done
