#! /opt/homebrew/bin/bash

# Get the directory that contains this script so it can be run from anywhere
# without breaking the symlinks.
thisDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## Search for opts and set flags/print info accordingly
while getopts ":fh" opt; do
    case "$opt" in
        f)
            force=true
            ;;
        h)
            echo
            echo "Usage: ./install [-f]"
            echo
            echo "The following options are available:"
            echo
            echo "    -f    Forces the installation of all settings files, overwriting any that already exist."
            echo "    -h    Displays help information"
            echo
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

# Setup a list of the files to install and where to install them to.
declare -A files

files["$HOME/.zshrc"]=zsh/.zshrc
files["$HOME/.zsh_styles"]=zsh/.zsh_styles
files["$HOME/.zsh_prompt"]=zsh/.zsh_prompt
files["$HOME/.zsh_aliases"]=zsh/.zsh_aliases
files["$HOME/.zsh_welcome"]=zsh/.zsh_welcome
files["$HOME/.zsh_osx"]=zsh/.zsh_osx
files["$HOME/.zsh_nix"]=zsh/.zsh_nix
files["$HOME/.zsh_windows"]=zsh/.zsh_windows

files["$HOME/.gitconfig"]=git/.gitconfig

# Iterate the list of files, installing each one or printing the reason for
# skipping installation.
for f in ${!files[@]}; do
    # if it doesn't exist, is a symlink, or installing with force, then install.
    if [[ ! -f "$f" ]] || [[ -L "$f" ]] || [[ "$force" = true ]]; then
        rm -rf "$f"
        ln -sf "$thisDir/${files[$f]}" "$f"
    else
        echo "$f is not a symbolic link, use -f or remove the file."
    fi
done
